dist: trusty
sudo: required
services:
- docker
language: go
go:
  - "1.13.x"

env:
  global:
    - GOFLAGS=-mod=vendor
    - LINUX_BINARY_PATH=${GOPATH}/bin/terraform-provider-github
    - DARWIN_BINARY_PATH=${GOPATH}/bin/darwin_amd64/terraform-provider-github

install:
- make tools

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  include:
  - name: "make lint"
    script: make lint
  - name: "make test"
    script: make test
  - name: "make website-lint"
    script: make website-lint
  - name: "make website-test"
    script: make website-test

before_deploy:
  - GIT_TAG=$(git describe --tags)
  - GOOS=linux GOARCH=amd64 make build
  - mv ${LINUX_BINARY_PATH} ${LINUX_BINARY_PATH}_${GIT_TAG}
  - zip -j ${LINUX_BINARY_PATH}_${GIT_TAG}_linux_amd64.zip ${LINUX_BINARY_PATH}_${GIT_TAG}
  - GOOS=darwin GOARCH=amd64 make build
  - mv ${DARWIN_BINARY_PATH} ${DARWIN_BINARY_PATH}_${GIT_TAG}
  - zip -j ${DARWIN_BINARY_PATH}_${GIT_TAG}_darwin_amd64.zip ${DARWIN_BINARY_PATH}_${GIT_TAG}

# Deploy only when a tag is created and pushed to the master branch.
deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file:
    - ${LINUX_BINARY_PATH}_${GIT_TAG}_linux_amd64.zip
    - ${DARWIN_BINARY_PATH}_${GIT_TAG}_darwin_amd64.zip
  skip_cleanup: true
  file_glob: true
  on:
    branch: master
    tags: true
  condition: ${GIT_TAG} =~ ^v[0-9]+\.[0-9]+\.[0-9]$ AND ${JOB_NAME} = "make test"
