dist: trusty
sudo: required
services:
- docker
language: go
go:
  - "1.13.x"

env:
  - GOFLAGS=-mod=vendor

branches:
  only:
  - master

install:
- make tools

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  include:
  - name: "make lint"
    script: make lint
  - name: "make test"
    script: make test
  - name: "make website-lint"
    script: make website-lint
