name: Acceptance Tests

on:
  pull_request:
    types: [labeled]

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name, ', '), 'acceptance-test')
    steps:

      - name: Parse Context From Environment
        run: |
          echo ::set-env name=HEAD_SHA::$(
            jq -rc '.pull_request.head.sha' $GITHUB_EVENT_PATH
          )
          echo ::set-env name=LABEL_NAME::$(
            jq -rc .label.name $GITHUB_EVENT_PATH
          )

      - name: Parse Arguments From Label Name
        run: |
          echo ::set-env name=RUN_FILTER::$(
            echo $LABEL_NAME | cut -d/ -f 2
          )
          if [[ "$LABEL_NAME" != *"TestAcc"* ]]; then exit 1; fi

      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          ref: ${{ env.HEAD_SHA }}

      - name: Generate Test Fixtures
        run: |
          openssl req -x509 -newkey rsa:4096 -days 1 -nodes \
            -subj "/C=US/ST=CA/L=San Francisco/O=HashiCorp, Inc./CN=untrusted" \
            -keyout github/test-fixtures/key.pem -out github/test-fixtures/cert.pem

      - name: Acceptance Tests
        uses: terraformtesting/acceptance-tests@v1.4.0
        with:
          RUN_FILTER: ${{ env.RUN_FILTER }}
          GITHUB_BASE_URL: "https://api.github.com/"
          GITHUB_OWNER: terraformtesting
          GITHUB_TEST_USER: github-terraform-test-user
          GITHUB_TEST_USER_NAME: "Test User"
          GITHUB_TEST_USER_EMAIL: 60107403+github-terraform-test-user@users.noreply.github.com
          GITHUB_TEST_USER_TOKEN: ${{ secrets.GITHUB_TEST_USER_TOKEN }}
          GITHUB_TEST_COLLABORATOR: github-terraform-test-collaborator
          GITHUB_TEST_COLLABORATOR_TOKEN: ${{ secrets.GITHUB_TEST_COLLABORATOR_TOKEN }}
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 23826477
