name: Dotcom Acceptance Tests (manual)

on:
  pull_request:

jobs:

  acceptance-tests-anonymous:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name, ', '), 'test/')
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Acceptance Tests (Anonymous)
        id: acceptance-tests-anonymous
        run: ./scripts/entrypoint.sh
        env:
          RUN_ALL: 'false'
          TF_LOG: INFO
          GITHUB_BASE_URL: https://api.github.com/
          GITHUB_TEST_ORGANIZATION: backmarket-sandbox-yli
          GITHUB_TEST_OWNER: stegayet
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 245841152
          GITHUB_TEST_USER_TOKEN: ${{ secrets.TEST_USER_TOKEN }}
      - name: Failed Acceptance Tests (Anonymous)
        if: ${{ failure() }}
        run: ./scripts/entrypoint.sh
        with:
          RUN_ALL: 'false'
          TF_LOG: DEBUG
          GITHUB_BASE_URL: https://api.github.com/
          GITHUB_TEST_ORGANIZATION: backmarket-sandbox-yli
          GITHUB_TEST_OWNER: stegayet
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 245841152
          GITHUB_TEST_USER_TOKEN: ${{ secrets.TEST_USER_TOKEN }}


  acceptance-tests-individual:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name, ', '), 'test')
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Acceptance Tests (Individual)
        id: acceptance-tests-individual
        run: ./scripts/entrypoint.sh
        env:
          RUN_ALL: 'false'
          TF_LOG: INFO
          GITHUB_OWNER: stegayet
          GITHUB_BASE_URL: https://api.github.com/
          GITHUB_TEST_ORGANIZATION: backmarket-sandbox-yli
          GITHUB_TEST_OWNER: stegayet
          GITHUB_TEST_USER_TOKEN: ${{ secrets.TEST_USER_TOKEN }}
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 245841152
      - name: Failed Acceptance Tests (Individual)
        id: acceptance-tests-individual
        run: ./scripts/entrypoint.sh
        if: ${{ failure() }}
        with:
          RUN_ALL: 'false'
          TF_LOG: DEBUG
          GITHUB_OWNER: stegayet
          GITHUB_BASE_URL: https://api.github.com/
          GITHUB_TEST_ORGANIZATION: backmarket-sandbox-yli
          GITHUB_TEST_OWNER: stegayet
          GITHUB_TEST_USER_TOKEN: ${{ secrets.TEST_USER_TOKEN}}
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 245841152

  acceptance-tests-organization:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name, ', '), 'test')
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Acceptance Tests (Organization)
        id: acceptance-tests-organization
        run: ./scripts/entrypoint.sh
        env:
          RUN_ALL: 'false'
          TF_LOG: INFO
          GITHUB_BASE_URL: https://api.github.com/
          GITHUB_ORGANIZATION: backmarket-sandbox-yli
          GITHUB_TEST_ORGANIZATION: backmarket-sandbox-yli
          GITHUB_TEST_USER_TOKEN: ${{ secrets.TEST_USER_TOKEN }}
          GITHUB_TEST_OWNER: stegayet
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 245841152

      - name: Failed Acceptance Tests (Organization)
        run: ./scripts/entrypoint.sh
        if: ${{ failure() }}
        with:
          RUN_ALL: 'false'
          TF_LOG: DEBUG
          GITHUB_BASE_URL: https://api.github.com/
          GITHUB_ORGANIZATION: backmarket-sandbox-yli
          GITHUB_TEST_ORGANIZATION: backmarket-sandbox-yli
          GITHUB_TEST_USER_TOKEN: ${{ secrets.TEST_USER_TOKEN }}
          GITHUB_TEST_OWNER: stegayet
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 245841152
