name: Dotcom Acceptance Tests (manual)

on:
  pull_request:
    types: [labeled]

jobs:

  acceptance-tests-anonymous:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name, ', '), 'test/')
    steps:
      - name: Parse Args
        id: args
        run: |
          echo "::set-output name=run_allowed::$(
            jq -rc .label.name $GITHUB_EVENT_PATH | cut -d/ -f 2
          )"
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Acceptance Tests (Anonymous)
        id: acceptance-tests-anonymous
        uses: terraformtesting/acceptance-tests@66f4842d934555dde0f59bf1a00abd0fc710ece4 # v2.2.0
        with:
          TF_LOG: INFO
          RUN_ALLOWED: ${{ steps.args.outputs.run_allowed }}
      - name: Failed Acceptance Tests (Anonymous)
        if: ${{ failure() }}
        uses: terraformtesting/acceptance-tests@66f4842d934555dde0f59bf1a00abd0fc710ece4 # v2.2.0
        with:
          TF_LOG: DEBUG
          RUN_ALLOWED: ${{ steps.acceptance-tests-anonymous.outputs.run_allowed }}


  acceptance-tests-individual:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name, ', '), 'test')
    steps:
      - name: Parse Args
        id: args
        run: |
          echo "::set-output name=run_allowed::$(
            jq -rc .label.name $GITHUB_EVENT_PATH | cut -d/ -f 2
          )"
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Acceptance Tests (Individual)
        id: acceptance-tests-individual
        uses: terraformtesting/acceptance-tests@66f4842d934555dde0f59bf1a00abd0fc710ece4 # v2.2.0
        with:
          TF_LOG: INFO
          RUN_ALLOWED: ${{ steps.args.outputs.run_allowed }}
          GITHUB_OWNER: github-terraform-test-user
          GITHUB_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }}
          GITHUB_TEST_ORGANIZATION: terraformtesting
      - name: Failed Acceptance Tests (Individual)
        if: ${{ failure() }}
        uses: terraformtesting/acceptance-tests@66f4842d934555dde0f59bf1a00abd0fc710ece4 # v2.2.0
        with:
          TF_LOG: DEBUG
          RUN_ALLOWED: ${{ steps.args.outputs.run_allowed }}
          GITHUB_OWNER: github-terraform-test-user
          GITHUB_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }}
          GITHUB_TEST_ORGANIZATION: terraformtesting

  acceptance-tests-organization:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name, ', '), 'test')
    steps:
      - name: Parse Args
        id: args
        run: |
          echo "::set-output name=run_allowed::$(
            jq -rc .label.name $GITHUB_EVENT_PATH | cut -d/ -f 2
          )"
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Acceptance Tests (Organization)
        id: acceptance-tests-organization
        uses: terraformtesting/acceptance-tests@66f4842d934555dde0f59bf1a00abd0fc710ece4 # v2.2.0
        with:
          TF_LOG: INFO
          RUN_ALLOWED: ${{ steps.args.outputs.run_allowed }}
          GITHUB_ORGANIZATION: terraformtesting
          GITHUB_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }}
          GITHUB_TEST_OWNER: github-terraform-test-user

      - name: Failed Acceptance Tests (Organization)
        uses: terraformtesting/acceptance-tests@66f4842d934555dde0f59bf1a00abd0fc710ece4 # v2.2.0
        if: ${{ failure() }}
        with:
          TF_LOG: DEBUG
          RUN_ALLOWED: ${{ steps.args.outputs.run_allowed }}
          GITHUB_ORGANIZATION: terraformtesting
          GITHUB_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }}
          GITHUB_TEST_OWNER: github-terraform-test-user
