name: Dotcom Acceptance Tests (All)

on:
  schedule:
    #         ┌───────────── minute (0 - 59)
    #         │ ┌───────────── hour (0 - 23)
    #         │ │ ┌───────────── day of the month (1 - 31)
    #         │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #         * * * * *
    - cron:  '0 0 * * *'

jobs:

  acceptance-tests-anonymous:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      - name: Acceptance Tests (Anonymous)
        uses: terraformtesting/acceptance-tests@v2.2.0
        with:
          TF_LOG: INFO
          RUN_ALL: true

  acceptance-tests-individual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2

      - name: Acceptance Tests (Individual)
        id: acceptance-tests-individual
        uses: terraformtesting/acceptance-tests@v2.2.0
        with:
          TF_LOG: INFO
          RUN_ALL: true
          GITHUB_OWNER: github-terraform-test-user
          GITHUB_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }}
          GITHUB_TEST_ORGANIZATION: terraformtesting

      - name: Failed Acceptance Tests (Individual)
        if: ${{ failure() }}
        uses: terraformtesting/acceptance-tests@v2.2.0
        with:
          TF_LOG: DEBUG
          RUN_ALLOWED: ${{ steps.acceptance-tests-individual.outputs.failed }}
          GITHUB_OWNER: github-terraform-test-user
          GITHUB_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }}
          GITHUB_TEST_ORGANIZATION: terraformtesting

  acceptance-tests-organization:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2

      - name: Acceptance Tests (Organization)
        id: acceptance-tests-organization
        uses: terraformtesting/acceptance-tests@v2.2.0
        with:
          TF_LOG: INFO
          RUN_ALL: true
          GITHUB_ORGANIZATION: terraformtesting
          GITHUB_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }}
          GITHUB_TEST_OWNER: github-terraform-test-user

      - name: Failed Acceptance Tests (Organization)
        uses: terraformtesting/acceptance-tests@v2.2.0
        if: ${{ failure() }}
        with:
          TF_LOG: DEBUG
          RUN_ALLOWED: ${{ steps.acceptance-tests-organization.outputs.failed }}
          GITHUB_ORGANIZATION: terraformtesting
          GITHUB_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }}
          GITHUB_TEST_OWNER: github-terraform-test-user
