name: Acceptance Tests (GHES)

on:
  workflow_dispatch:
  # pull_request_target:
  #   types:
  #     - opened
  #     - synchronize
  #     - reopened
  #     - labeled
  #   branches:
  #     - main
  #     - release-v*

permissions: read-all

jobs:
  test:
    name: Test GHES
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: acctest-ghes
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Check secrets
        env:
          INPUT_ALLOWED_SECRETS: ${{ vars.GHES_ACCEPTANCE_TESTS_ALLOWED_SECRETS || 'GHES_TEST_USER_TOKEN' }}
          INPUT_SECRETS: ${{ toJSON(secrets) }}
        run: |
          set -eou pipefail

          secret_keys="$(jq --raw-output --compact-output '[. | keys[] | select(test("^(?:(?:ACTIONS)|(?:actions)|(?:GITHUB)|(?:github)|(?:TEST)|(?:test))_") | not)] | sort | join(",")' <<<"${INPUT_SECRETS}")"
          if [[ "${secret_keys}" != "${INPUT_ALLOWED_SECRETS}" ]]; then
            echo "::error::Too many or too few secrets configured: ${secret_keys}"
            exit 1
          fi

      - name: Check server address
        id: server
        env:
          GHES_TEST_SERVER_HOST: ${{ vars.GHES_TEST_SERVER_HOST }}
        run: |
          set -eou pipefail

          host="${GHES_TEST_SERVER_HOST}"

          if [[ -z "${host}" ]]; then
            echo "::error::Missing GHES server address"
            exit 1
          fi

          test="$(dig +short "${host}")"

          if [[ "${test}" != "255.255.255.255" ]]; then
            echo "Invalid server address" >&2
            exit 1
          fi

          echo "address=https://${host}/" >> "${GITHUB_OUTPUT}"

      - name: Check credentials
        id: credentials
        env:
          TEST_USER_TOKEN: ${{ secrets.GHES_TEST_USER_TOKEN  }}
        run: |
          set -eou pipefail

          if [[ -z "${TEST_USER_TOKEN}" ]]; then
            echo "::error::Missing credentials"
            exit 1
          fi

          echo "token=${TEST_USER_TOKEN}" >> "${GITHUB_OUTPUT}"

      - name: Set-up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        env:
          TF_ACC: "1"
          TF_LOG: INFO
          GITHUB_TOKEN: ${{ steps.credentials.outputs.token }}
          GITHUB_BASE_URL: ${{ steps.server.outputs.address }}
          GITHUB_TEST_TYPE: enterprise
          GITHUB_OWNER: terraformtesting
          GITHUB_ORGANIZATION: terraformtesting
          GITHUB_TEST_USER_TOKEN: ${{ steps.credentials.outputs.token }}
        run: go test -run "^TestAcc*" ./github -v -race -coverprofile=coverage.txt -covermode=atomic -timeout 120m -count=1

  check:
    name: Check GHES Acceptance Tests
    if: always() && github.event_name == 'pull_request'
    needs:
      - test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check
        env:
          INPUT_RESULTS: ${{ join(needs.*.result, ' ') }}
        run: |
          set -euo pipefail
          read -a results <<< "${INPUT_RESULTS}"
          for result in "${results[@]}"; do
            if [[ "${result}" == "failure" ]] || [[ "${result}" == "cancelled" ]]; then
              echo "::error::Workflow failed!"
              exit 1
            fi
          done
