name: GHES Acceptance Tests

on:
  push:
    branches:
      - test/**

jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Query server address
        id: server-address
        run: |
          SERVER_ADDRESS=$(dig +short terraformtesting-ghe.eastus.cloudapp.azure.com)
          echo "::set-output name=server-address::${SERVER_ADDRESS}"
    outputs:
      server-address:  ${{ steps.server-address.outputs.server-address }}

  acceptance-tests-anonymous:
    needs: [runtime]
    if: ${{ needs.runtime.outputs.server-address != '255.255.255.255' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      - name: Acceptance Tests (Anonymous)
        uses: terraformtesting/acceptance-tests@v2.2.0
        with:
          GITHUB_BASE_URL: "https://terraformtesting-ghe.eastus.cloudapp.azure.com/"

  acceptance-tests-individual:
    needs: [runtime]
    if: ${{ needs.runtime.outputs.server-address != '255.255.255.255' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      - name: Acceptance Tests (Individual)
        uses: terraformtesting/acceptance-tests@v2.2.0
        with:
          GITHUB_BASE_URL: "https://terraformtesting-ghe.eastus.cloudapp.azure.com/"
          GITHUB_OWNER: administrator
          GITHUB_TEST_USER_TOKEN: ${{ secrets.GHES_TEST_USER_TOKEN }}

  acceptance-tests-organization:
    needs: [runtime]
    if: ${{ needs.runtime.outputs.server-address != '255.255.255.255' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      - name: Acceptance Tests (Organization)
        uses: terraformtesting/acceptance-tests@v2.2.0
        with:
          GITHUB_BASE_URL: "https://terraformtesting-ghe.eastus.cloudapp.azure.com/"
          GITHUB_ORGANIZATION: terraformtesting
          GITHUB_TEST_USER_TOKEN: ${{ secrets.GHES_TEST_USER_TOKEN }}
