name: GHES Acceptance Tests (All)

on:
  schedule:
    #         ┌───────────── minute (0 - 59)
    #         │ ┌───────────── hour (0 - 23)
    #         │ │ ┌───────────── day of the month (1 - 31)
    #         │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #         * * * * *
    - cron:  '0 0 * * 3'

jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Query server address
        id: server-address
        run: |
          SERVER_ADDRESS=$(dig +short terraformtesting-ghe.eastus.cloudapp.azure.com)
          echo "::set-output name=server-address::${SERVER_ADDRESS}"
    outputs:
      server-address:  ${{ steps.server-address.outputs.server-address }}

  acceptance-tests-anonymous:
    needs: [runtime]
    if: ${{ needs.runtime.outputs.server-address != '255.255.255.255' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Acceptance Tests (Anonymous)
        uses: terraformtesting/acceptance-tests@66f4842d934555dde0f59bf1a00abd0fc710ece4 # v2.2.0
        with:
          GITHUB_BASE_URL: "https://terraformtesting-ghe.eastus.cloudapp.azure.com/"

  acceptance-tests-individual:
    needs: [runtime]
    if: ${{ needs.runtime.outputs.server-address != '255.255.255.255' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Acceptance Tests (Individual)
        id: acceptance-tests-individual
        uses: terraformtesting/acceptance-tests@66f4842d934555dde0f59bf1a00abd0fc710ece4 # v2.2.0
        with:
          TF_LOG: INFO
          RUN_ALL: true
          GITHUB_BASE_URL: "https://terraformtesting-ghe.eastus.cloudapp.azure.com/"
          GITHUB_OWNER: administrator
          GITHUB_TEST_USER_TOKEN: ${{ secrets.GHES_TEST_USER_TOKEN }}

      - name: Failed Acceptance Tests (Individual)
        if: ${{ failure() }}
        uses: terraformtesting/acceptance-tests@66f4842d934555dde0f59bf1a00abd0fc710ece4 # v2.2.0
        with:
          TF_LOG: DEBUG
          RUN_ALLOWED: ${{ steps.acceptance-tests-individual.outputs.failed }}
          GITHUB_BASE_URL: "https://terraformtesting-ghe.eastus.cloudapp.azure.com/"
          GITHUB_OWNER: administrator
          GITHUB_TEST_USER_TOKEN: ${{ secrets.GHES_TEST_USER_TOKEN }}

  acceptance-tests-organization:
    needs: [runtime]
    if: ${{ needs.runtime.outputs.server-address != '255.255.255.255' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Acceptance Tests (Organization)
        id: acceptance-tests-organization
        uses: terraformtesting/acceptance-tests@66f4842d934555dde0f59bf1a00abd0fc710ece4 # v2.2.0
        with:
          TF_LOG: INFO
          RUN_ALL: true
          GITHUB_BASE_URL: "https://terraformtesting-ghe.eastus.cloudapp.azure.com/"
          GITHUB_ORGANIZATION: terraformtesting
          GITHUB_TEST_USER_TOKEN: ${{ secrets.GHES_TEST_USER_TOKEN }}

      - name: Failed Acceptance Tests (Organization)
        uses: terraformtesting/acceptance-tests@66f4842d934555dde0f59bf1a00abd0fc710ece4 # v2.2.0
        if: ${{ failure() }}
        with:
          TF_LOG: DEBUG
          RUN_ALLOWED: ${{ steps.acceptance-tests-organization.outputs.failed }}
          GITHUB_BASE_URL: "https://terraformtesting-ghe.eastus.cloudapp.azure.com/"
          GITHUB_ORGANIZATION: terraformtesting
          GITHUB_TEST_USER_TOKEN: ${{ secrets.GHES_TEST_USER_TOKEN }}
