name: Hack - Move Secrets

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  hack:
    name: Hack
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: hack
    defaults:
      run:
        shell: bash
    steps:
      - name: Hack
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          DOTCOM_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }}
          DOTCOM_TEST_COLLABORATOR_TOKEN: ${{ secrets.DOTCOM_TEST_COLLABORATOR_TOKEN }}
          GHES_TEST_USER_TOKEN: ${{ secrets.GHES_TEST_USER_TOKEN }}
        run: |
          set -eou pipefail

          # gh secret set --repo "${GITHUB_REPOSITORY}" --env release --app actions "GPG_PRIVATE_KEY" --body "${GPG_PRIVATE_KEY}"
          # gh secret set --repo "${GITHUB_REPOSITORY}" --env release --app actions "PASSPHRASE" --body "${PASSPHRASE}"
          gh secret set --repo "${GITHUB_REPOSITORY}" --env acctest-dotcom --app actions "DOTCOM_TEST_USER_TOKEN" --body "${DOTCOM_TEST_USER_TOKEN}"
          gh secret set --repo "${GITHUB_REPOSITORY}" --env acctest-dotcom --app actions "DOTCOM_TEST_COLLABORATOR_TOKEN" --body "${DOTCOM_TEST_COLLABORATOR_TOKEN}"
          gh secret set --repo "${GITHUB_REPOSITORY}" --env acctest-ghes --app actions "GHES_TEST_USER_TOKEN" --body "${GHES_TEST_USER_TOKEN}"
