name: Hack - Move Secrets

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  hack:
    name: Hack
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: hack
    defaults:
      run:
        shell: bash
    steps:
      - name: Hack
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          set -eou pipefail

          gh secret set --repo "${GITHUB_REPOSITORY}" --env release --app actions "GPG_PRIVATE_KEY" --body "${GPG_PRIVATE_KEY}"
          gh secret set --repo "${GITHUB_REPOSITORY}" --env release --app actions "PASSPHRASE" --body "${PASSPHRASE}"
